flags: {}
extra-package-dbs: []
packages:
- '.'
- ../uniform/uniform-strings
- ../uniform/uniform-algebras
- ../uniform/uniform-convenience
- ../uniform/uniform-fileio
- ../uniform/uniform-error

# - ../fromOthers/glabrous

extra-deps:
- test-invariant-0.4.5.0
- twitch-0.1.7.2
# - spawn-0.3
resolver: lts-12.26  # 26 seems to have a problem with pandoc
