flags: {}
extra-package-dbs: []
packages:
- '.'
- ../uniform/uniform-strings
- ../uniform/uniform-algebras
- ../uniform/uniform-convenience
- ../uniform/uniform-fileio
- ../uniform/uniform-error
- ../fromOthers/bibtex

# - ../fromOthers/glabrous

extra-deps:
- test-invariant-0.4.5.0
- twitch-0.1.7.2
- yaml-union-0.0.3
- shake-ext-3.1.0.0
# - spawn-0.3
# - fsutils-0.1.2
resolver: lts-12.26  # 26 seems to have a problem with pandoc
