
storage:
    themeDir:  /home/frank/Workspace8/ssg/theme
    doughDir: /home/frank/Workspace8/ssg/site/dough
    bakedDir: /home/frank/Workspace8/ssg/site/baked
    reportFile: /home/frank/reportBakeAll.txt
    testDir: /home/frank/SSG

